### ISSUE TITLE
an error message in the middle of processing

### ISSUE THREAD

**Issue by ucok66** [tsurumeso/waifu2x-chainer#14]
when I tried to enlarge my 132 images with this command
`python waifu2x.py -a 3 -e png -q 8 -b 8 -l 128 -m noise_scale -s 4 -n 3 -i /home/ucok66/material/4 -o /home/ucok66/waifu
`
i got this message
```
Traceback (most recent call last):
  File "waifu2x.py", line 175, in <module>
    src = Image.open(path)
  File "/usr/lib/python3.7/site-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/ucok66/material/4/.directory'
```
did i did something wrong?

**Comment by tsurumeso** [comment]
Maybe it was fixed. Thank you for letting me know.
