### ISSUE TITLE
[Bug] cannot write file as WebP. Wait, what?

### ISSUE THREAD

**Issue by ucok66** [tsurumeso/waifu2x-chainer#19]
Hai, I found this bug.
```
Traceback (most recent call last):
  File "waifu2x.py", line 224, in <module>
    icc_profile=icc_profile)
  File "/home/ucok66/.local/lib/python2.7/site-packages/PIL/Image.py", line 2007, in save
    save_handler(self, fp, filename)
  File "/home/ucok66/.local/lib/python2.7/site-packages/PIL/WebPImagePlugin.py", line 342, in _save
    raise IOError("cannot write file as WebP (encoder returned None)")
IOError: cannot write file as WebP (encoder returned None)
```

**Comment by tsurumeso** [comment]
Does this happens with certain image? If It is, please provide the problem image.
If this happens with any images, I will investigate it.

**Comment by ucok66** [comment]
Sorry, this is my fault, I upscaled image that beyond [what WEBP can handle](https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be). I was tried to upscale a comic four time bigger than the original, here the image reverence that I use
![episode_26__books_are_great_by_deevad](https://user-images.githubusercontent.com/46832396/58382374-8f54f180-7ff3-11e9-84b6-851cd0ba1130.jpg)

**Comment by ucok66** [comment]
I think it is safe to close this Issue now
