### ISSUE TITLE
training problems

### ISSUE THREAD

**Issue by Jerchongkong** [tsurumeso/waifu2x-chainer#20]
Hello m8, when I try to train a custom model, this error appears and I do not know how to solve it.

> * loading filelist... done
> * setup model... done
> * check forward path... done
> * starting processes of dataset sampler... done
> ### epoch: 0 ###
>   # inner epoch: 0
> Process Process-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/content/waifu2x-chainer/lib/dataset_sampler.py", line 85, in _worker
>     xc_batch, yc_batch = pairwise_transform(img, cfg)
>   File "/content/waifu2x-chainer/lib/pairwise_transform.py", line 148, in pairwise_transform
>     cfg.nr_rate, cfg.chroma_subsampling_rate, cfg.noise_level)
>   File "/content/waifu2x-chainer/lib/pairwise_transform.py", line 66, in noise_scale
>     with iproc.array_to_wand(src) as tmp:
>   File "/content/waifu2x-chainer/lib/iproc.py", line 75, in array_to_wand
>     dst = wand.image.Image(blob=buf.getvalue())
> NameError: name 'wand' is not defined
> Process Process-2:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/content/waifu2x-chainer/lib/dataset_sampler.py", line 85, in _worker
>     xc_batch, yc_batch = pairwise_transform(img, cfg)
>   File "/content/waifu2x-chainer/lib/pairwise_transform.py", line 148, in pairwise_transform
>     cfg.nr_rate, cfg.chroma_subsampling_rate, cfg.noise_level)
>   File "/content/waifu2x-chainer/lib/pairwise_transform.py", line 66, in noise_scale
>     with iproc.array_to_wand(src) as tmp:
>   File "/content/waifu2x-chainer/lib/iproc.py", line 75, in array_to_wand
>     dst = wand.image.Image(blob=buf.getvalue())
> NameError: name 'wand' is not defined

Wand is the cause of the problem.
I use ubuntu 18.04 and cuda 10.0

**Comment by tsurumeso** [comment]
Please install wand.
http://docs.wand-py.org/en/0.5.4/
