### ISSUE TITLE
Train a model with 2 imputs.

### ISSUE THREAD

**Issue by Jerchongkong** [tsurumeso/waifu2x-chainer#23]
Hi m8, I have prepared a extensive dataset divided into 2 folders, in the "A" folder with low-resolution pictures and the "B" folder where are the high-clean-resolution ones.
I want to train my own model to achieve a super-resolution task.

Is it possible to do that feat?

**Comment by tsurumeso** [comment]
Yes it is. But I have no plans to implement that feat at the moment.
