### ISSUE TITLE
[Feature Request] Use without gpu

### ISSUE THREAD

**Issue by hirios** [tsurumeso/waifu2x-chainer#25]
First, congratulations on the code!
Is it possible to work without graphics cards? How can I do this?

**Comment by tsurumeso** [comment]
You can run on CPU to omit `--gpu` (`-g`) option.
Sorry for the late response.

**Comment by hirios** [comment]
@tsurumeso
Many thanks for the feedback !! I was able to make it work by following what you said. <3: 3
