### ISSUE TITLE
出力先に画像を指定した場合の挙動

### ISSUE THREAD

**Issue by f11894** [tsurumeso/waifu2x-chainer#3]
出力先に画像を指定した場合の挙動に関して要望があります。
以下のようなコマンドを実行した場合、

python waifu2x.py -m scale -s 2 -i "C:\waifu2x\001.png" -a 2 -o "C:\waifu2x\001_hoge.png"

画像の出力先は次のようになってしまいます。
C:\waifu2x\001_hoge.png\001_(scale2.0x)(resnet10_rgb).png

この動作は仕様なのかもしれませんが-oで指定した場所に出力出来るようになるとありがたいです。
ご検討いただけないでしょうか？

**Comment by tsurumeso** [comment]
ご要望の通り --output オプションの挙動を変更しましたのでご確認ください．
同名のファイルが既に存在する場合は，従来の命名規則に従ってファイル名を決定し保存する仕様としました．
これでいかがでしょう？

**Comment by f11894** [comment]
ありがとうございます。
