### ISSUE TITLE
一部の種類のアルファチャンネルの画像の拡大に失敗する

### ISSUE THREAD

**Issue by f11894** [tsurumeso/waifu2x-chainer#4]
例えば以下のような画像です

https://www.pictcake.jp/images/chara/hatsunemiku/top_illust.png
https://twitter.com/koza_game/status/941205937733255168

ログには以下のように表示されます

C:\Users\***\Anaconda3\lib\site-packages\PIL\Image.py:888: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images

**Comment by tsurumeso** [comment]
バグ報告ありがとうございます．修正しました．
