### ISSUE TITLE
photoモデルのサポート

### ISSUE THREAD

**Issue by kenin0726** [tsurumeso/waifu2x-chainer#7]
photoモデルを対応する計画がありますか？
ResNet10で、photoモデルを使ってみたいです。

**Comment by tsurumeso** [comment]
申し訳ありませんが，学習リソースが足りないためphotoモデルの対応予定はありません．もし必要であればご自身でモデルを学習していただくことになります．

**Comment by kenin0726** [comment]
やはりトレインしたデーターによってanimeとかphotoとか決定されるのでしょうか。
コメントありがとうございます。

**Comment by tsurumeso** [comment]
その通りです．現在公開しているモデルは6000枚のイラストをデータセットとして学習したものになります．Photoモデルを学習する場合は同程度の規模の自然画像データセットを用意する必要があります。
