### ISSUE TITLE
how to deal with variable input and output

### ISSUE THREAD

**Issue by GitRainy** [tsurumeso/waifu2x-chainer#8]
I learn about that the cnn can handle the variable input,but we want get the output sizes is different for different inputs.What can I do?

**Comment by tsurumeso** [comment]
Fully convolutional network that does not contain dense layer just applies filters to input image, so it can handle variable inputs.

**Comment by GitRainy** [comment]
Oh,thanks,I an reading and testing the code then I understand the data-processing ,Now I have some 
 trouble with ClippedWeightedHuberLoss(loss function),I can understand the forward function but I can‘t understand the backward function,so can you give me some inspiration。（My english is very poor,233）

**Comment by tsurumeso** [comment]
Definition is [here](https://docs.chainer.org/en/stable/reference/generated/chainer.functions.huber_loss.html).

<img src="https://latex.codecogs.com/gif.latex?\frac{\partial{L_{\delta}}}{\partial{x}}=\frac{\partial{L_{\delta}}}{\partial{a}}\frac{\partial{a}}{\partial{x}}"/>
<img src="https://latex.codecogs.com/gif.latex?\frac{\partial{L_{\delta}}}{\partial{t}}=\frac{\partial{L_{\delta}}}{\partial{a}}\frac{\partial{a}}{\partial{t}}"/>
